### ISSUE TITLE
The module MMM-Currentweather-MQTT is not displayed on the Smart

### ISSUE THREAD

**Issue by maximiliano2018** [spitzlbergerj/MMM-Currentweather-MQTT#1]
Hello!
Maybe you can help me, I think I have everything correctly installed, but I can't see the module appear on the Smart.

My config
{ 
			module: "MMM-Currentweather-MQTT",
			position: "top_right",
			config: {				
				location: "Haedo",
				locationID: "3430545",  //ID from http://bulk.openweathermap.org/sample/; unzip the gz file and find your city
				appid: "7679f84b5f444",
		        roundTemp: true,
				degreeLabel: true,
				showWindDirection: true,
				showWindDirectionAsArrow: true,
				showHumidity: true,
				showFeelsLike: false,
				useBeaufort: false,
				useKMPHwind: true,
                logging: true,
                useWildcards: false,
        mqttServers: [
            {
                address: '192.168.100.154',    // Server address or IP address
		 		        port: '1883',          // Port number if other than default
				subscriptions: [
					{
						topic: 'ESPURNA-FA874C/temperature',  // Topic to look for
						label: 'Temperature',       // Displayed in front of value
						suffix: 'C',              // Displayed after the value
						decimals: 0,               // Round numbers to this number of decimals
						sortOrder: 10,             // Can be used to sort entries in the same table
						maxAgeSeconds: 6000,        // Reduce intensity if value is older
					},
					
			{
						topic: 'ESPURNA-FA874C/humidity',  // Topic to look for
						label: 'Humidity',       // Displayed in front of value
						suffix: 'C',              // Displayed after the value
						decimals: 1,               // Round numbers to this number of decimals
						sortOrder: 10,             // Can be used to sort entries in the same table
						maxAgeSeconds: 6000,        // Reduce intensity if value is older
					},	

DOS window log
MM-Currentweather-MQTT: Adding server:  { address: '192.168.100.154',
  port: '1883',
  subscriptions:
   [ { topic: 'ESPURNA-FA874C/temperature',
       label: 'Temperature',
       suffix: 'C',
       decimals: 0,
       sortOrder: 10,
       maxAgeSeconds: 6000 },
     { topic: 'ESPURNA-FA874C/humidity',
       label: 'Humidity',
       suffix: 'C',
       decimals: 1,
       sortOrder: 10,
       maxAgeSeconds: 6000 } ] }
MMM-Currentweather-MQTT: Starting client for:  { serverKey: '192.168.100.154:1883',
  address: '192.168.100.154',
  port: '1883',
  options: {},
  topics: [ 'ESPURNA-FA874C/temperature', 'ESPURNA-FA874C/humidity' ] }
MMM-Currentweather-MQTT: Connecting to mqtt://192.168.100.154:1883
Creating new MQTT client for url:  mqtt://192.168.100.154:1883

I can only see the classic weather module!
Any ideas?
Thank you!

**Comment by spitzlbergerj** [comment]
Good morning,

my module looks in the display exactly like the original module currentweather. Only the values are exchanged with the local values, if values are delivered via MQTT.

To test it, it is best to display the original module and my module. Usually the values differ slightly. Then it is clear that values are processed and displayed via MQTT.

Many greetings

Sepp

Von: maximiliano2018 <notifications@github.com>
Gesendet: Donnerstag, 16. April 2020 03:30
An: spitzlbergerj/MMM-Currentweather-MQTT <MMM-Currentweather-MQTT@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [spitzlbergerj/MMM-Currentweather-MQTT] The module MMM-Currentweather-MQTT is not displayed on the Smart (#1)


Hello!
Maybe you can help me, I think I have everything correctly installed, but I can't see the module appear on the Smart.

My config
{
module: "MMM-Currentweather-MQTT",
position: "top_right",
config: {
location: "Haedo",
locationID: "3430545", //ID from http://bulk.openweathermap.org/sample/; unzip the gz file and find your city
appid: "76796c67b4e1f9d2e40516ef84b5f444",
roundTemp: true,
degreeLabel: true,
showWindDirection: true,
showWindDirectionAsArrow: true,
showHumidity: true,
showFeelsLike: false,
useBeaufort: false,
useKMPHwind: true,
logging: true,
useWildcards: false,
mqttServers: [
{
address: '192.168.100.154', // Server address or IP address
port: '1883', // Port number if other than default
subscriptions: [
{
topic: 'ESPURNA-FA874C/temperature', // Topic to look for
label: 'Temperature', // Displayed in front of value
suffix: 'C', // Displayed after the value
decimals: 0, // Round numbers to this number of decimals
sortOrder: 10, // Can be used to sort entries in the same table
maxAgeSeconds: 6000, // Reduce intensity if value is older
},

               {

                                      topic: 'ESPURNA-FA874C/humidity',  // Topic to look for

                                      label: 'Humidity',       // Displayed in front of value

                                      suffix: 'C',              // Displayed after the value

                                      decimals: 1,               // Round numbers to this number of decimals

                                      sortOrder: 10,             // Can be used to sort entries in the same table

                                      maxAgeSeconds: 6000,        // Reduce intensity if value is older

                               },

DOS window log
MM-Currentweather-MQTT: Adding server: { address: '192.168.100.154',
port: '1883',
subscriptions:
[ { topic: 'ESPURNA-FA874C/temperature',
label: 'Temperature',
suffix: 'C',
decimals: 0,
sortOrder: 10,
maxAgeSeconds: 6000 },
{ topic: 'ESPURNA-FA874C/humidity',
label: 'Humidity',
suffix: 'C',
decimals: 1,
sortOrder: 10,
maxAgeSeconds: 6000 } ] }
MMM-Currentweather-MQTT: Starting client for: { serverKey: '192.168.100.154:1883',
address: '192.168.100.154',
port: '1883',
options: {},
topics: [ 'ESPURNA-FA874C/temperature', 'ESPURNA-FA874C/humidity' ] }
MMM-Currentweather-MQTT: Connecting to mqtt://192.168.100.154:1883
Creating new MQTT client for url: mqtt://192.168.100.154:1883

I can only see the classic weather module!
Any ideas?
Thank you!

**Comment by maximiliano2018** [comment]
Hello again!
I'm testing it like this, with the two modules active, currentweather and MMM-Currentweather-MQTT, but only the original (currentweather) is shown.

It also gave an error when lifting the Json;
Failed to load resource: the server responded with a status of 404 (Not Found)
http: // localhost: 8080 / modules / MMM-Currentweather-MQTT / translations / en.json

To fix it, modify the translation directory to translationS and it was fixed, but I can't get the information to be seen in the Smart.
Maybe any idea where to look for the error?
Thank you so much!

**Comment by spitzlbergerj** [comment]
HI, maximiliano2018,

you are right. That was a mistake. TRhe directory should bei named translations. Now I've renamed it. Thanks.

I just reloaded the module via git clone and restarted the mirror. The module appears immediately and shows the correct values.

Unfortunately I can't reproduce the error. Sorry. So I don't really know how to help you.

What do the pm2 log files under /home/pi/.pm2/logs say?

**Comment by maximiliano2018** [comment]
Hi Sepp!

I could find it!
If you comment on at least one of the subscriptions, for example the rain one, the module is no longer visible, or at least that happens to me.
The only way it works is if you copy and paste the example config as it is defined in github.
Maybe it would be nice if it only showed those topics that are defined in config.
Maybe you can replicate it by just commenting (//) the following lines and leaving the rest without commenting.


// {
// topic: 'wetter / rain-today',
// label: 'Regenmenge heute',
// suffix: '',
// decimals: 0,
// sortOrder: 70,
// maxAgeSeconds: 600,
//},

Please tell me later if you wish!
Cheers!
Max

**Comment by spitzlbergerj** [comment]
Hello, Max,

please help me troubleshoot.

Open the Chrome Browser. There start the page http://<IP-MagicMirror:8080/. Then click into the mirror display with the right mouse button and choose examine (or CTRL-Shift-I)

Then you should get a debug interface. In the lower half you can see the errors. See Scrrendump

Do you have any for MMM-Currentweather-MQTT?
If so, which errors are reported?

Maybe I can find out. Thanks for the help.

Many greetings

Sepp

![ScreenShot 20200419134212 MagicMirror² - Google Chrome](https://user-images.githubusercontent.com/38983450/79686851-9906c980-8243-11ea-995b-b2b87df1fcf4.jpg)

**Comment by maximiliano2018** [comment]
Hi Sepp;

Apologies for not having answered you before, these are the errors that appear to me.

jsonpointer.js:91 Uncaught ReferenceError: exports is not defined
    at jsonpointer.js:91
topics_match.js:14 Uncaught ReferenceError: module is not defined
    at topics_match.js:14
2localhost/:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Class.updateWeather (MMM-Currentweather-MQTT.js:479)
    at Class.socketNotificationReceived (MMM-Currentweather-MQTT.js:836)
    at module.js:246
    at r.<anonymous> (socketclient.js:25)
    at r.emit (index.js:83)
    at r.onevent (index.js:83)
    at r.MMSocket.self.socket.onevent (socketclient.js:19)
    at r.onpacket (index.js:83)
    at r.<anonymous> (index.js:83)
MMM-Currentweather-MQTT.js:668 Uncaught TypeError: Cannot read property 'value' of undefined
    at Class.processWeather (MMM-Currentweather-MQTT.js:668)
    at XMLHttpRequest.weatherRequest.onreadystatechange (MMM-Currentweather-MQTT.js:492)
MMM-Hotword.js:249 Uncaught TypeError: Cannot set property 'innerHTML' of null
    at Class.status (MMM-Hotword.js:249)
    at Class.socketNotificationReceived (MMM-Hotword.js:149)
    at module.js:246
    at r.<anonymous> (socketclient.js:25)
    at r.emit (index.js:83)
    at r.onevent (index.js:83)
    at r.MMSocket.self.socket.onevent (socketclient.js:19)
    at r.onpacket (index.js:83)
    at r.<anonymous> (index.js:83)
    at r.emit (index.js:83)
2MMM-Currentweather-MQTT.js:668 Uncaught TypeError: Cannot read property 'value' of undefined
    at Class.processWeather (MMM-Currentweather-MQTT.js:668)
    at Class.updateWeather (MMM-Currentweather-MQTT.js:479)
    at Class.socketNotificationReceived (MMM-Currentweather-MQTT.js:836)
    at module.js:246
    at r.<anonymous> (socketclient.js:25)
    at r.emit (index.js:83)
    at r.onevent (index.js:83)
    at r.MMSocket.self.socket.onevent (socketclient.js:19)
    at r.onpacket (index.js:83)
    at r.<anonymous> (index.js:83)
4MMM-Currentweather-MQTT.js:668 Uncaught TypeError: Cannot read property 'value' of undefined
    at Class.processWeather (MMM-Currentweather-MQTT.js:668)
    at Class.updateWeather (MMM-Currentweather-MQTT.js:479)
    at Class.socketNotificationReceived (MMM-Currentweather-MQTT.js:836)
    at module.js:246
    at r.<anonymous> (socketclient.js:25)
    at r.emit (index.js:83)
    at r.onevent (index.js:83)
    at r.MMSocket.self.socket.onevent (socketclient.js:19)
    at r.onpacket (index.js:83)
    at r.<anonymous> (index.js:83)
processWeather @ MMM-Currentweather-MQTT.js:668
updateWeather @ MMM-Currentweather-MQTT.js:479
socketNotificationReceived @ MMM-Currentweather-MQTT.js:836
(anonymous) @ module.js:246
(anonymous) @ socketclient.js:25
r.emit @ index.js:83
r.onevent @ index.js:83
MMSocket.self.socket.onevent @ socketclient.js:19
r.onpacket @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.ondecoded @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
a.add @ index.js:83
r.ondata @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onPacket @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onPacket @ index.js:83
r.onData @ index.js:83
ws.onmessage @ index.js:83


The above happens with these commented lines of the config, if I uncomment them, everything works well.

		{ 
			module: "MMM-Currentweather-MQTT",
			position: "top_left",
			config: {				
				location: "Haedo",
				locationID: "3430545",  //ID from http://bulk.openweathermap.org/sample/; unzip the gz file and find your city
				appid: "76796c67b4e1f9d2e40516ef84b5f444",
		        roundTemp: true,
				degreeLabel: true,
				showWindDirection: true,
				showWindDirectionAsArrow: true,
				showHumidity: true,
				showFeelsLike: true,
				useBeaufort: true,
				useKMPHwind: true,
               logging: true,
                useWildcards: true,
       mqttServers: [
            {
                address: '192.168.100.154',    // Server address or IP address
		 		   port: '1883',          // Port number if other than default
				subscriptions: [

			{
						topic: 'ESPURNA-FA874C/temperature',  // Topic to look for
						label: 'Temperatura',                 // Displayed in front of value
						suffix: '°C',                         // Displayed after the value
						decimals: 1,                          // Round numbers to this number of decimals
						sortOrder: 10,                        // Can be used to sort entries in the same table
						maxAgeSeconds: 600,                   // Reduce intensity if value is older
					},
					{
						topic: 'ESPURNA-FA874C/humidity',
						label: 'Humedad',
						suffix: '%',
						decimals: 1,
						sortOrder: 20,
						maxAgeSeconds: 600
					},
					{
						topic: 'wetter/act-illum',
						label: 'Helligkeit',
						sortOrder: 30,
						maxAgeSeconds: 600
					},
					
					{
						topic: 'wetter/act-wind-speed',
						label: 'Windgeschwindigkeit',
						suffix: 'km/h',
						decimals: 0,
						sortOrder: 40,
						maxAgeSeconds: 600
					},

					{
						topic: 'wetter/act-wind-dir',
						label: 'Windrichtung',
						suffix: '°',
						decimals: 0,
						sortOrder: 50,
						maxAgeSeconds: 600
					},

					{
						topic: 'wetter/raining',
						label: 'Regnet es?',
						suffix: '',
						decimals: 0,
						sortOrder: 60,
						maxAgeSeconds: 600,
						conversions: [
							{ from: "true", to: "ja" },
							{ from: "false", to: "nein" }
						]
					},

//					{
//						topic: 'wetter/rain-today',
//						label: 'Regenmenge heute',
//						suffix: '',
//						decimals: 0,
//						sortOrder: 70,
//						maxAgeSeconds: 600,
//					},	
					
					

                               ]
			}
       ],
	},
	},


Thanks Sepp, I hope I have been helpful.
Max

**Comment by spitzlbergerj** [comment]
Hi,
I was able to fix the first mistake (JSON). But I can't eliminate the other error so easily at the moment. But it will not occur if you consider the following:
For now, all seven values must be specified in the config, even if they are not delivered and not displayed.
Please try this.
With the showXyz values you can still determine what should be displayed. 
Sorry for this quick and dirty solution. I don't have more time right now.
