### ISSUE TITLE
I cannot connect to the broker

### ISSUE THREAD

**Issue by majdzik84** [spitzlbergerj/MMM-Currentweather-MQTT#2]
I can't connect to my mosquito broker where I have login and password. What should the configuration look like? Can you help me?

`{
	module: "MMM-Currentweather-MQTT",
	position: "top_right",
	config: {
		location: "XYZ",
		locationID: "1234567",
		appid: "<yourAppID>",
		roundTemp: true,
		degreeLabel: true,
		showWindDirection: true,
		showWindDirectionAsArrow: true,
		showHumidity: true,
		showFeelsLike: false,
		useBeaufort: false,
		useKMPHwind: true,
		logging: true,
		useWildcards: false,
                **mqttServerAddress: '192.168.2.98', ???????????
               mqttServerPort : '1883', ???????
                mqttServerUser : 'user',
                mqttServerPassword : 'password',**
		mqttServers: [
			{
				address: 'xxx.xxx.xxx.xxx',  // Server address or IP address  ???????????
				port: '1883',                // Port number if other than default ?????????
				subscriptions: [             // for now, all seven values must be 
				                             // specified in the config, 
							     // even if they are not delivered and not displayed.
					{

**Comment by spitzlbergerj** [comment]
Hi,
the MQTT part I have taken over to a large extent from the module MMM-MQTT https://github.com/ottopaulsen/MMM-MQTT Can you try this module first. The settings there should also work here.
Otherwise I have little experience with a MQTT server that requires authentication. Sorry
Regards
Josef

**Comment by spitzlbergerj** [comment]
Hi again,
I took a quick look at the code. The authentication is done by config values address, port, user and password.

I'll adapt the documentation. Sorry for giving wrong values.

 can you please try it like this?

**Comment by majdzik84** [comment]
Hi. thank you. it works perfectly.
